title:             Southern Cross Brigade
email:             southerncrossbrigade@gmail.com
description:       28 December 2019 - 17 January 2020
author:            ACFS
baseurl:           "/"
url:               "https://southern-cross-brigade.github.io"

# Social Profiles
# twitter_username:  SBootstrap
# github_username:   BlackrockDigital
facebook_username: southerncrossbrigade/
instagram_username: southerncrossbrigadetocuba

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
